version: 2
workflows:
  version: 2
  create-snapshot:
    jobs:
      - deploy-and-create-snapshot:
          filters:
            branches:
              only:
                - update-dss-deploy-scripts
                - circleci-config
jobs:
  deploy-and-create-snapshot:
    docker:
      - image: levity/dapptools-node-latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build new snapshot
          command: |
            source /home/circleci/setup-env.sh
            yarn deploy-mcd:ci
            yarn create-default-snapshot
            yarn commit-and-push