#!/usr/bin/env bash
set -e

CWD="${0%/*}"
LIB=$CWD/../lib
OUT=$CWD/../out

mkdir -p $OUT

ls $LIB/dss-deploy/out/*.abi | \
  grep -v -E "(Dev|Test|t_sol)" | \
  xargs sh -c "cp \$@ $OUT" placeholder

# for an explanation of the placeholder arg above, see:
# https://en.wikipedia.org/wiki/Xargs#Shell_trick
