#!/usr/bin/env bash
set -e

CWD="${0%/*}"
LIB=$CWD/../lib
OUT=$CWD/../out

mkdir -p $OUT/mcd

cp $LIB/maker-otc/out/MatchingMarket.abi \
  $LIB/ds-proxy/out/DSProxy.abi \
  $LIB/ds-proxy/out/DSProxyFactory.abi \
  $LIB/sai-proxy/out/SaiProxyCreateAndExecute.abi \
  $LIB/proxy-registry/out/ProxyRegistry.abi \
  $LIB/oasis-direct-proxy/out/ProxyCreationAndExecute.abi \
$OUT

ls $LIB/sai/out/*.abi | \
  grep -v -E "(Fab|Dev|Test|t_sol)" | \
  xargs sh -c "cp \$@ $OUT" placeholder

ls $LIB/dss-proxy-actions/out/*.abi | \
  grep -v -E "(Fab|Dev|Test|t_sol)" | \
  xargs sh -c "cp \$@ $OUT/mcd" placeholder

# for an explanation of the placeholder arg above, see:
# https://en.wikipedia.org/wiki/Xargs#Shell_trick
