#!/usr/bin/env bash

function jq_inplace {
  TMP=$(mktemp)
  jq "$1" "$2" > $TMP && mv $TMP "$2"
}

function sed_inplace {
  # sed's -i argument behaves differently on macOS, hence this hack
  sed -i.bak "$1" $2 && rm $2.bak
}

function deploy_mcd_dds {
  DDS=$LIB/dss-deploy-scripts
  cd $DDS

  export MCD_PAUSE_DELAY=0

  TMP=$(mktemp)

  # change deploy-testchain not to send 10000 ETH
  sed_inplace 's/10000 eth/1 eth/' deploy-testchain.sh

  # submodule contracts are deprecated; this nix command
  # installs all necessary dependencies
  nix run -f $DDS -c deploy-testchain.sh

  # uncomment below to add more ilks
  # DPA=$LIB/testchain-dss-deployment-scripts/contracts/dss-proxy-actions
  # cd $DPA/lib/dss-cdp-manager/lib/dss-deploy/
  # export DAPP_SOLC_VERSION=0.5.0
  # . bin/deploy-ilk-col1 B
  # . bin/deploy-ilk-eth B

  ls \
    $DDS/out/abi/* \
    $DDS/contracts/dss-deploy/out/*.abi | \
    grep -v -E "(Fab|Dev|Test|Like|t_sol|lib_|src_)" | \
    xargs sh -c "cp \$@ $OUT/mcd" placeholder
  # why the placeholder? see https://en.wikipedia.org/wiki/Xargs#Shell_trick

  # sort addresses alphabetically
  jq -S . $DDS/out/addresses.json > $OUT/addresses-mcd.json

  # all done, go home!
  cd -
}
