#!/usr/bin/env bash

function jq_inplace {
  TMP=$(mktemp)
  jq "$1" > $TMP && mv $TMP "$2"
}

function sed_inplace {
  # sed's -i argument behaves differently on macOS, hence this hack
  sed -i.bak "$1" $2 && rm $2.bak
}

function deploy_mcd_dds {
  DDS=$LIB/dss-deploy-scripts
  cd $DDS

  export MCD_PAUSE_DELAY=0

  TMP=$(mktemp)

  # change testchain.json to not send 10000 ETH
  # This isn't correct--where does this happen now?
  sed_inplace 's/10000 eth/1 eth/' config/testchain.json

  # deploy migration contracts with local tub and gem
  TUB=$(cat $OUT/addresses.json | jq '.TUB')
  GEM=$(cat $OUT/addresses.json | jq '.GEM')
  GOV=$(cat $OUT/addresses.json | jq '.GOV')
  DEPLOY=$DDS/config/testchain.json
  cat $DEPLOY | jq_inplace ".migration = $(<$LIB/deploy-migration.json)" $DEPLOY
  cat $DEPLOY | jq_inplace ".migration.tub = $(echo $TUB)" $DEPLOY
  cat $DEPLOY | jq_inplace ".tokens.ETH.gem = $(echo $GEM)" $DEPLOY
  cat $DEPLOY | jq_inplace ".gov = $(echo $GOV)" $DEPLOY
  echo "here"
  # submodule contracts are deprecated; this nix command
  # installs all necessary dependencies
  ETH_RPC_URL="http://localhost:2000" nix run -f ./ -c dss-deploy testchain

  # uncomment below to add more ilks
  # DPA=$LIB/testchain-dss-deployment-scripts/contracts/dss-proxy-actions
  # cd $DPA/lib/dss-cdp-manager/lib/dss-deploy/
  # export DAPP_SOLC_VERSION=0.5.0
  # . bin/deploy-ilk-col1 B
  # . bin/deploy-ilk-eth B

  ls \
    $DDS/out/abi/* \
    $DDS/contracts/dss-deploy/out/*.abi | \
    grep -v -E "(Fab|Dev|Test|Like|t_sol|lib_|src_)" | \
    xargs sh -c "cp \$@ $OUT/mcd" placeholder
  # why the placeholder? see https://en.wikipedia.org/wiki/Xargs#Shell_trick

  # sort addresses alphabetically
  jq -S . $DDS/out/addresses.json > $OUT/addresses-mcd.json

  # all done, go home!
  cd -
}
