#!/usr/bin/env bash
set -e

CWD="${0%/*}"
LIB=$CWD/../lib
OUT=$CWD/../out
DEPLOYMENT_OUTPUT=json
TEMPLATE=""
PORT=2000

# parse arguments
while [[ "$#" > 0 ]]; do case $1 in
  -o|--output) DEPLOYMENT_OUTPUT="$2"; shift;;
  -p|--port) PORT="$2"; shift;;
  --template) TEMPLATE="$2"; shift;;
esac; shift; done


# Pre check output format before doing something
if ! [[ "$DEPLOYMENT_OUTPUT" =~ ^(json|env|yaml|yml)$ ]]; then
  if [ ! -f "$TEMPLATE" ]; then
    echo "Template file $TEMPLATE - does not exist"
    exit 1
  fi
fi

mkdir -p $OUT

cd $LIB/dss-deploy/
source bin/deploy-all
cd -

# Output functions file
source $CWD/output

case "$DEPLOYMENT_OUTPUT" in
  json)
    write_json "$OUT/addresses.json"
    ;;
  yaml|yml)
    write_yaml "$OUT/addresses.yaml"
    ;;
  env)
    write_env "$OUT/addresses"
    ;;
  *)
    copy_template "$TEMPLATE" "$DEPLOYMENT_OUTPUT"
    write_template "$DEPLOYMENT_OUTPUT"
    ;;
esac

$CWD/collect-abis
