#!/usr/bin/env bash

function sed_inplace {
  # sed's -i argument behaves differently on macOS, hence this hack
  sed -i.bak "$1" $2 && rm $2.bak
}

function write_json_scd {
  if [ -z "$1" ]; then
    echo "No output file passed. Use write_json path/to/file.json"
    exit 1
  fi

  echo "Publishing output into $1"
  cat > $1 <<- EOM
{
  "ETH_FROM": "$ETH_FROM",
  "GEM": "$SAI_GEM",
  "GOV": "$SAI_GOV",
  "PIP": "$SAI_PIP",
  "PEP": "$SAI_PEP",
  "PIT": "$SAI_PIT",
  "ADM": "$SAI_ADM",
  "SAI": "$SAI_SAI",
  "SIN": "$SAI_SIN",
  "SKR": "$SAI_SKR",
  "DAD": "$SAI_DAD",
  "MOM": "$SAI_MOM",
  "VOX": "$SAI_VOX",
  "TUB": "$SAI_TUB",
  "TAP": "$SAI_TAP",
  "TOP": "$SAI_TOP",
  "MAKER_OTC": "$OTC",
  "PROXY_REGISTRY": "$PROXY_REGISTRY",
  "DS_PROXY": "$DS_PROXY",
  "SAI_PROXY": "$SAI_PROXY",
  "OASIS_PROXY": "$OASIS_PROXY",
  "REDEEMER": "$REDEEMER",
  "OLD_MKR": "$OLD_MKR",
  "OLD_CHIEF": "$OLD_CHIEF",
  "OLD_IOU": "$OLD_IOU",
  "POLLING": "$POLLING",
  "BATCH_POLLING": "$BATCH_POLLING",
  "OLD_VOTE_PROXY_FACTORY": "$OLD_VOTE_PROXY_FACTORY",
  "LINE_SPELL": "$LINE_SPELL",
  "SAI_CAGEFREE": "$CAGEFREE"
}
EOM
}

function deploy_scd {
  # Fix sai deploy scripts (deploy and deploy-fab)
  sed_inplace '13s/DSToken.*/WETH9)/' $LIB/sai/bin/deploy
  sed_inplace 's/=0x/=/g' $LIB/sai/bin/deploy 
  #sed_inplace 's/build/build --extract/g' $LIB/sai/bin/deploy 
  sed_inplace 's/build/build --optimize/g' $LIB/sai/bin/deploy 
  #sed_inplace 's/build/build --extract/g' $LIB/sai/bin/deploy-fab 

  # Change sai deploy scripts to skip dapp build if SKIP_BUILD_IF_ALREADY_BUILT is set and dapp is already built
  sed_inplace 's/^dapp build$/if [[ -z "$SKIP_BUILD_IF_ALREADY_BUILT" || ( -n "$SKIP_BUILD_IF_ALREADY_BUILT" \&\& ! -f out\/SaiTop.abi ) ]]; then dapp build; fi/' $LIB/sai/bin/deploy-fab
  sed_inplace 's/^dapp build$/# dapp build/' $LIB/sai/bin/deploy

  # Prebuild
  cd $LIB/maker-otc
  echo "building maker otc"
  dapp update
  dapp --use solc:0.5.12 build || true

  cd $LIB/proxy-registry
  echo "building proxy reg"
  dapp update
  dapp --use solc:0.5.0 build || true

  cd $LIB/sai-proxy
  echo "sap prox"
  dapp update
  dapp --use solc:0.4.25 build || true

  cd $LIB/oasis-direct-proxy
  echo "building oasis direct"
  dapp update
  dapp --use solc:0.4.25 build || true

  cd $LIB/ds-token
  # dapp update
  echo "building ds token"
  dapp update
  dapp --use solc:0.4.25 build || true

  cd $LIB/maker-499
  echo "building maker 488"
  dapp update
  dapp --use solc:0.4.25 build || true

  cd $LIB/ds-chief
  echo "building ds chief"
  # dapp update
  dapp update
  dapp --use solc:0.5.0 build || true

  cd  $LIB/symbolic-voting
  echo "building symbolic"
  # dapp update
  dapp update
  dapp --use solc:0.5.0 build || true

  cd $LIB/vote-proxy
  echo "building vote proxy old"
  # dapp update
  dapp update
  dapp --use solc:0.5.0 build || true

  cd $LIB/line-spell
  echo "building line spell"
  dapp update
  dapp update
  dapp --use solc:0.5.12 build || true

  cd $LIB/sai-cagefree
  # dapp update
  echo "building cagefree"
  dapp update
  dapp --use solc:0.5.15 build || true

  cd $LIB/sai
  # dapp update
  echo "building SAI"
  dapp update
  dapp --use solc:0.4.25 build --optimize || true

  ############################
  # build sai

  cd $LIB/sai
  if [[ -z "$SKIP_BUILD_IF_ALREADY_BUILT" || ( -n "$SKIP_BUILD_IF_ALREADY_BUILT" && ! -f out/SaiTop.abi ) ]]; then
    echo "Building and deploying sai contracts..."
  else
    echo "Deploying sai contracts..."
  fi
  bin/deploy-fab && . load-fab-unknown
  bin/deploy     && . load-env-unknown
  
  # Set the ETH price feed to 400 USD
  seth send $SAI_PIP "poke(bytes32)" 0x000000000000000000000000000000000000000000000015af1d78b58c400000
  # Set the MKR price feed to 1040.49 USD
  seth send $SAI_PEP "poke(bytes32)" 0x00000000000000000000000000000000000000000000003867bb3260a7cf7200
  seth send $SAI_MOM "setCap(uint256)" $(seth --to-uint256 $(seth --to-wei 1000 eth))
  # Mint MKR, owned by default account
  seth send $SAI_GOV "mint(uint256)" 0x000000000000000000000000000000000000000000000015af1d78b58c400000
  cd -

  ############################
  # build oasis

  export SOLC_FLAGS=${SOLC_FLAGS:-"--optimize"}
  cd $LIB/maker-otc
  # if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ] && [ -f out/MatchingMarket.abi ]; then
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for maker-otc (already built)"
  else
    echo "Building maker-otc..."
    dapp --use solc:0.5.12 build --extract
  fi
  echo "Deploying maker-otc (MatchingMarket)..."
  OTC=$(dapp create MatchingMarket 1893459661) # This is some random date in 2030
  cd -

  ############################
  # build proxy registry

  cd $LIB/proxy-registry
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for proxy-registry (already built)"
  else
    echo "Building proxy-registry..."
    dapp --use solc:0.5.0 build --extract
  fi
  echo "Deploying ProxyRegistry and DSProxyFactory..."
  DS_PROXY_FACTORY=$(dapp create DSProxyFactory)
  echo "Deployed DSProxyFactory to $DS_PROXY_FACTORY"

  PROXY_REGISTRY=$(dapp create ProxyRegistry $DS_PROXY_FACTORY)
  echo "Deployed ProxyRegistry to $PROXY_REGISTRY"

  echo "Creating DSProxy via ProxyRegistry.build()..."
  DS_PROXY="0x"$(seth --abi-decode "build()(address)" $(seth call $PROXY_REGISTRY "build()")) # Get expected address of new DSProxy instance about to be created
  seth send $PROXY_REGISTRY "build()"
  echo "Created new DSProxy instance with address: $DS_PROXY"
  cd -

  ############################
  # build sai proxy

  cd $LIB/sai-proxy
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for sai-proxy (already built)"
  else
    echo "Building sai-proxy..."
    dapp --use solc:0.4.25 build --extract
  fi
  echo "Deploying sai-proxy (SaiProxyCreateAndExecute)..."
  SAI_PROXY=$(dapp create SaiProxyCreateAndExecute)
  echo "Deployed SaiProxyCreateAndExecute to $SAI_PROXY"
  cd -

  ############################
  # build oasis proxy

  cd $LIB/oasis-direct-proxy
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for oasis-direct-proxy (already built)"
  else
    echo "Building oasis-direct-proxy..."
    dapp --use solc:0.4.25 build --extract
  fi
  echo "Deploying oasis-direct-proxy (ProxyCreationAndExecute)..."
  SAI_GEM=$(cat $OUT/addresses.json | jq --raw-output '.GEM')
  OASIS_PROXY=$(dapp create ProxyCreationAndExecute $SAI_GEM)
  echo "Deployed ProxyCreationAndExecute to $OASIS_PROXY"
  cd -

  ############################
  # build maker redeemer

  # deploy a DSToken stand-in for old MKR
  cd $LIB/ds-token
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for old MKR token (already built)"
  else
    dapp update
    echo "Building old MKR token..."
    dapp --use solc:0.4.25 build
  fi
  
  echo "Deploying old MKR token..."
  OLD_MKR=$(dapp create DSToken $(seth --to-bytes32 $(seth --from-ascii 'OLD_MKR')))
  echo "Deployed old MKR to $OLD_MKR"
  seth send $OLD_MKR "mint(address,uint256)" $ETH_FROM 0x000000000000000000000000000000000000000000000015af1d78b58c400000
  cd -

  cd $LIB/maker-499
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for MKR redeemer (already built)"
  else
    echo "Building MKR redeemer..."
    dapp --use solc:0.4.25 build --extract
  fi
  echo "Deploying MKR redeemer..."
  REDEEMER=$(dapp create Redeemer $OLD_MKR $SAI_GOV $(seth --to-hex 2000000000))
  echo "Deployed MKR redeemer to $REDEEMER"
  cd -

  ############################
  # build old chief

  cd $LIB/ds-chief
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for Old Chief (already built)"
  else
    echo "Building Old Chief..."
    dapp update
    dapp --use solc:0.5.0 build --extract
  fi
  export SETH_ASYNC=yes
  echo "Creating OLD_IOU token..."
  test -z $OLD_IOU && IOUtx=$(dapp create DSToken $(seth --to-bytes32 $(seth --from-ascii 'IOU')))
  export SETH_ASYNC=no
  echo "Setting OLD_IOU address..."
  test -z $OLD_IOU && OLD_IOU=$(seth receipt $IOUtx contractAddress)
  MAX_YAYS=5
  echo "Creating OLD_CHIEF token..."
  OLD_CHIEF=$(dapp create DSChief $SAI_GOV $OLD_IOU $MAX_YAYS)
  seth send $OLD_IOU 'setOwner(address)' $OLD_CHIEF
  echo "Deployed old DSChief to $OLD_CHIEF and old IOU to $OLD_IOU"

  ############################
  # build polling emitter

  cd  $LIB/symbolic-voting
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for PollingEmitter (already built)"
  else
    echo "Building PollingEmitter..."
    dapp update
    dapp --use solc:0.5.0 build --extract
  fi

  # The polling contract is deployed twice to represent
  # the legacy polling contract
  POLLING=$(dapp create PollingEmitter)
  BATCH_POLLING=$(dapp create PollingEmitter)
  cd -

  ############################
  # build vote proxy factory

  cd $LIB/vote-proxy
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for Old VoteProxyFactory (already built)"
  else
    echo "Building Old VoteProxyFactory..."
    dapp update
    dapp --use solc:0.5.0 build --extract
  fi
  OLD_VOTE_PROXY_FACTORY=$(dapp create VoteProxyFactory $OLD_CHIEF)
  cd -

  ############################
  # build line-spell

  # This spell will not work for anything but reading basic variables.
  # If you need a working spell, it will need to be added to deploy-mcd,
  # and the following placeholder variables will need to be corrected.

  PAUSE="0xe82ce3d6bf40f2f9414c8d01a35e3d9eb16a1761"
  PLAN="0xe82ce3d6bf40f2f9414c8d01a35e3d9eb16a1761"
  VAT="0xe82ce3d6bf40f2f9414c8d01a35e3d9eb16a1761"
  ILK=$(seth --to-bytes32 "0x4241542d41")
  LINE=100000000

  cd $LIB/line-spell
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for LineSpell (already built)"
  else
    echo "Building LineSpell..."
    dapp update
    dapp --use solc:0.5.12 build --extract
  fi
  LINE_SPELL=$(dapp create LineSpell $PAUSE $PLAN $VAT $ILK $LINE)
  cd -

  ############################
  # build sai cagefree

  cd $LIB/sai-cagefree
  if [ -n "$SKIP_BUILD_IF_ALREADY_BUILT" ]; then
    echo "Skipping dapp build for CageFree (already built)"
  else
    echo "Building CageFree..."
    dapp update
    dapp --use solc:0.5.15 build --extract
  fi
  CAGEFREE=$(dapp create CageFree $SAI_TAP $SAI_GEM)
  cd -

  ############################
  # copy contract abis and addresses

  # Rebuild each contract with --extract flag to get the ABIs we need
  # The --extract flag causes the script to exit, adding "|| true" allows us to keep going.
  cd $LIB/maker-otc
  echo "building maker otc"
  dapp --use solc:0.5.12 build --extract || true

  cd $LIB/proxy-registry
  echo "building proxy reg"
  dapp --use solc:0.5.0 build --extract || true

  cd $LIB/sai-proxy
  echo "sap prox"
  dapp --use solc:0.4.25 build --extract || true

  cd $LIB/oasis-direct-proxy
  echo "building oasis direct"
  dapp --use solc:0.4.25 build --extract || true

  cd $LIB/ds-token
  # dapp update
  echo "building ds token"
  dapp --use solc:0.4.25 build --extract || true

  cd $LIB/maker-499
  echo "building maker 488"
  dapp --use solc:0.4.25 build --extract || true

  cd $LIB/ds-chief
  echo "building ds chief"
  # dapp update
  dapp --use solc:0.5.0 build --extract || true

  cd  $LIB/symbolic-voting
  echo "building symbolic"
  # dapp update
  dapp --use solc:0.5.0 build --extract || true

  cd $LIB/vote-proxy
  echo "building vote proxy old"
  # dapp update
  dapp --use solc:0.5.0 build --extract || true

  cd $LIB/line-spell
  echo "building line spell"
  dapp update
  dapp --use solc:0.5.12 build --extract || true

  cd $LIB/sai-cagefree
  # dapp update
  echo "building cagefree"
  dapp --use solc:0.5.15 build --extract || true

  cd $LIB/sai
  # dapp update
  echo "building SAI"
  dapp --use solc:0.4.25 build --extract || true

  mkdir -p $OUT
  write_json_scd "$OUT/addresses.json"

  cp $LIB/maker-otc/out/MatchingMarket.abi \
  $LIB/sai-proxy/out/SaiProxyCreateAndExecute.abi \
  $LIB/proxy-registry/out/ProxyRegistry.abi \
  $LIB/proxy-registry/out/DSProxy.abi \
  $LIB/proxy-registry/out/DSProxyFactory.abi \
  $LIB/oasis-direct-proxy/out/ProxyCreationAndExecute.abi \
  $LIB/maker-499/out/Redeemer.abi \
  $LIB/ds-chief/out/DSChief.abi \
  $LIB/symbolic-voting/out/PollingEmitter.abi \
  $LIB/vote-proxy/out/VoteProxyFactory.abi \
  $LIB/line-spell/out/LineSpell.abi \
  $LIB/sai-cagefree/out/CageFree.abi \
  $OUT

  ls $LIB/sai/out/*.abi | \
  grep -v -E "(Fab|Dev|Test|t_sol)" | \
  xargs sh -c "cp \$@ $OUT" placeholder

  # for an explanation of the placeholder arg above, see:
  # https://en.wikipedia.org/wiki/Xargs#Shell_trick
}