#!/usr/bin/env bash
set -e

CWD="${0%/*}"
LIB=$CWD/../lib
OUT=$CWD/../out

# parse arguments
while [[ "$#" > 0 ]]; do case $1 in
  --scd-only) SCD_ONLY=1;;
  --mcd-only) MCD_ONLY=1;;
esac; shift; done

if [ -z $MCD_ONLY ]; then
  . $CWD/deploy-scd
  deploy_scd
fi

if [ -z $SCD_ONLY ]; then
  . $CWD/deploy-mcd
  deploy_mcd_tdds
fi
