#!/usr/bin/env bash

HOST="127.0.0.1"

function write_json 
{
  if [ -z "$1" ]; then
    echo "No output file passed. Use write_json path/to/file.json"
    exit 1
  fi

  echo "Publishing output into $1"
  cat > $1 <<- EOM
{
  "ETH_RPC_URL": "127.0.01:$PORT",
  "ETH_FROM": "$ETH_FROM",
  "GEM": "$SAI_GEM",
  "GOV": "$SAI_GOV",
  "PIP": "$SAI_PIP",
  "PEP": "$SAI_PEP",
  "PIT": "$SAI_PIT",
  "ADM": "$SAI_ADM",
  "SAI": "$SAI_SAI",
  "SIN": "$SAI_SIN",
  "SKR": "$SAI_SKR",
  "DAD": "$SAI_DAD",
  "MOM": "$SAI_MOM",
  "VOX": "$SAI_VOX",
  "TUB": "$SAI_TUB",
  "TAP": "$SAI_TAP",
  "TOP": "$SAI_TOP",
  "MAKER_OTC": "$OTC",
  "DS_PROXY_FACTORY": "$DS_PROXY_FACTORY",
  "PROXY_REGISTRY": "$PROXY_REGISTRY",
  "DS_PROXY": "$DS_PROXY",
  "SAI_PROXY": "$SAI_PROXY",
  "OASIS_PROXY": "$OASIS_PROXY"
}
EOM
}

function write_env 
{
  
  if [ -z "$1" ]; then
    echo "No output file passed. Use write_json path/to/file.json"
    exit 1
  fi

  echo "Publishing output into $1"
  cat > $1 <<- EOM
#!/usr/bin/env bash

export ETH_RPC_URL="127.0.0.1:$PORT"
export ETH_FROM=$ETH_FROM
export GEM="$SAI_GEM"
export GOV="$SAI_GOV"
export PIP="$SAI_PIP"
export PEP="$SAI_PEP"
export PIT="$SAI_PIT"
export ADM="$SAI_ADM"
export SAI="$SAI_SAI"
export SIN="$SAI_SIN"
export SKR="$SAI_SKR"
export DAD="$SAI_DAD"
export MOM="$SAI_MOM"
export VOX="$SAI_VOX"
export TUB="$SAI_TUB"
export TAP="$SAI_TAP"
export TOP="$SAI_TOP"
export MAKER_OTC="$OTC"
export DS_PROXY_FACTORY="$DS_PROXY_FACTORY"
export PROXY_REGISTRY="$PROXY_REGISTRY"
export DS_PROXY="$DS_PROXY"
export SAI_PROXY="$SAI_PROXY"
export OASIS_PROXY="$OASIS_PROXY"

EOM
}

function write_yaml
{
  if [ -z "$1" ]; then
    echo "No output file passed. Use write_json path/to/file.json"
    exit 1
  fi

  echo "Publishing output into $1"
  cat > $1 <<- EOM
rpc_url: "127.0.0.1:$PORT"
eth_from: "$ETH_FROM"
gem: "$SAI_GEM"
gov: "$SAI_GOV"
pip: "$SAI_PIP"
pep: "$SAI_PEP"
pit: "$SAI_PIT"
adm: "$SAI_ADM"
sai: "$SAI_SAI"
sin: "$SAI_SIN"
skr: "$SAI_SKR"
dad: "$SAI_DAD"
mom: "$SAI_MOM"
vox: "$SAI_VOX"
tub: "$SAI_TUB"
tap: "$SAI_TAP"
top: "$SAI_TOP"
maker_otc: "$OTC"
ds_proxy_factory: "$DS_PROXY_FACTORY"
proxy_registry: "$PROXY_REGISTRY"
ds_proxy: "$DS_PROXY"
sai_proxy: "$SAI_PROXY"
oasis_proxy: "$OASIS_PROXY"
EOM
}

function copy_template
{
  if [ -z "$1" ] || [ -z "$2" ]; then
    echo "No input or output file passed. Use copy_template path/to/input.template path/to/output.any"
    exit 1
  fi

  if [ -f "$2" ]; then
    echo "Output configuration file already exist. Delete it [y/n] ?"
    read yn
    if [[ $yn =~ ^[Yy]$ ]]; then
      rm "$2"
    else
      echo "Nothing else to do! Exiting..."
      exit 1
    fi
  fi
  cp $1 $2
}

function write_template
{
  if [ -z "$1" ]; then
    echo "No output file passed. Use write_template path/to/file.any"
    exit 1
  fi

  echo "Publishing output into $1"
  
  sed -i -e "s/{{TESTCHAIN_ETH_FROM}}/$ETH_FROM/g" $1
  sed -i -e "s/{{TESTCHAIN_HOST}}/$HOST/g" $1
  sed -i -e "s/{{TESTCHAIN_PORT}}/$PORT/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_GEM}}/$SAI_GEM/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_GOV}}/$SAI_GOV/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_PIP}}/$SAI_PIP/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_PEP}}/$SAI_PEP/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_PIT}}/$SAI_PIT/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_ADM}}/$SAI_ADM/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_SAI}}/$SAI_SAI/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_SIN}}/$SAI_SIN/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_SKR}}/$SAI_SKR/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_DAD}}/$SAI_DAD/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_MOM}}/$SAI_MOM/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_VOX}}/$SAI_VOX/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_TUB}}/$SAI_TUB/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_TAP}}/$SAI_TAP/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_TOP}}/$SAI_TOP/g" $1
  sed -i -e "s/{{TESTCHAIN_OTC}}/$OTC/g" $1
  sed -i -e "s/{{TESTCHAIN_DS_PROXY_FACTORY}}/$DS_PROXY_FACTORY/g" $1
  sed -i -e "s/{{TESTCHAIN_PROXY_REGISTRY}}/$PROXY_REGISTRY/g" $1
  sed -i -e "s/{{TESTCHAIN_DS_PROXY}}/$DS_PROXY/g" $1
  sed -i -e "s/{{TESTCHAIN_SAI_PROXY}}/$SAI_PROXY/g" $1

  # For osx `sed -i -e` will create new file $1-e and we have to remove it.
  if [ -f "$1-e" ]; then
    rm -f "$1-e"
  fi
}
