#!/usr/bin/env bash

function write_json 
{
  if [ -z "$1" ]; then
    echo "No output file passed. Use write_json path/to/file.json"
    exit 1
  fi

  echo "Publishing output into $1"
  cat > $1 <<- EOM
{
  "GEM": "$SAI_GEM",
  "GOV": "$SAI_GOV",
  "PIP": "$SAI_PIP",
  "PEP": "$SAI_PEP",
  "PIT": "$SAI_PIT",
  "ADM": "$SAI_ADM",
  "SAI": "$SAI_SAI",
  "SIN": "$SAI_SIN",
  "SKR": "$SAI_SKR",
  "DAD": "$SAI_DAD",
  "MOM": "$SAI_MOM",
  "VOX": "$SAI_VOX",
  "TUB": "$SAI_TUB",
  "TAP": "$SAI_TAP",
  "TOP": "$SAI_TOP",
  "MAKER_OTC": "$OTC",
  "DS_PROXY_FACTORY": "$DS_PROXY_FACTORY",
  "PROXY_REGISTRY": "$PROXY_REGISTRY",
  "DS_PROXY": "$DS_PROXY",
  "SAI_PROXY": "$SAI_PROXY"
}
EOM
}

function write_env 
{
  
  if [ -z "$1" ]; then
    echo "No output file passed. Use write_json path/to/file.json"
    exit 1
  fi

  echo "Publishing output into $1"
  cat > $1 <<- EOM
#!/usr/bin/env bash

export ETH_RPC_URL="127.0.0.1:$PORT"
export GEM="$SAI_GEM"
export GOV="$SAI_GOV"
export PIP="$SAI_PIP"
export PEP="$SAI_PEP"
export PIT="$SAI_PIT"
export ADM="$SAI_ADM"
export SAI="$SAI_SAI"
export SIN="$SAI_SIN"
export SKR="$SAI_SKR"
export DAD="$SAI_DAD"
export MOM="$SAI_MOM"
export VOX="$SAI_VOX"
export TUB="$SAI_TUB"
export TAP="$SAI_TAP"
export TOP="$SAI_TOP"
export MAKER_OTC="$OTC"
export DS_PROXY_FACTORY="$DS_PROXY_FACTORY"
export PROXY_REGISTRY="$PROXY_REGISTRY"
export DS_PROXY="$DS_PROXY"
export SAI_PROXY="$SAI_PROXY"

EOM
}

function write_yaml
{
  if [ -z "$1" ]; then
    echo "No output file passed. Use write_json path/to/file.json"
    exit 1
  fi

  echo "Publishing output into $1"
  cat > $1 <<- EOM
rpc_url: "127.0.0.1:$PORT"
gem: "$SAI_GEM"
gov: "$SAI_GOV"
pip: "$SAI_PIP"
pep: "$SAI_PEP"
pit: "$SAI_PIT"
adm: "$SAI_ADM"
sai: "$SAI_SAI"
sin: "$SAI_SIN"
skr: "$SAI_SKR"
dad: "$SAI_DAD"
mom: "$SAI_MOM"
vox: "$SAI_VOX"
tub: "$SAI_TUB"
tap: "$SAI_TAP"
top: "$SAI_TOP"
maker_otc: "$OTC"
ds_proxy_factory: "$DS_PROXY_FACTORY"
proxy_registry: "$PROXY_REGISTRY"
ds_proxy: "$DS_PROXY"
sai_proxy: "$SAI_PROXY"
EOM
}
